### ISSUE TITLE
Builds for Raspberry Pi?

### ISSUE THREAD

**Issue by probonopd** [surge-synthesizer/stochas#104]
This is a follow-up to https://github.com/surge-synthesizer/stochas/issues/74.
Are builds for the Raspberry Pi available for download, or could it be considered to make such builds available for download?
Thank you very much for considering.

**Comment by baconpaul** [comment]
Unfortunately we don’t have ci resources which are native pi. I suppose we could cross compile but I’m not entirely sure how to do that. If you have a cross compile ubuntu 20 set of packages and command lines though that would be the first step

**Comment by probonopd** [comment]
Would using GitHub Actions be an option for the ARM CI builds?

**Comment by rudeog** [comment]
I'm not sure about github actions as I've never used them. However I think it could be added to our CI on ubuntu and downloading the cross compiling resources as Paul said. @probonopd if you want to take a stab at it feel free. If you get something working we can add it.

**Comment by baconpaul** [comment]
Yeah gha and azure are roughly the same
I think the answer is: can we do a successful build cross compiled on ubuntu20? If so we can do same in azure. But I don’t know if we can! 

A shell script which does apt gets and cmake var sets and results in an aarch64 binary means we can make a downloadable asset (stochas surge and short circuit and Monique all!) so would be a welcomed bit of work. Easy to integrate thst into ci if it works

**Comment by probonopd** [comment]
Is there a complete list of dependencies (packages) somewhere? I am asking because the build script is assuming `cmake` and `git` to be there but it does not install them using apt... are there more packages like these?

WIP: https://github.com/probonopd/stochas/blob/patch-1/.github/workflows/arm_build.yml

WIP Builds: https://github.com/probonopd/stochas/actions

**Comment by baconpaul** [comment]
Our fully automated builds are here yeah https://github.com/surge-synthesizer/stochas/blob/a5480ab73e6dbe1b4f4f7da9692ac41d2e04d60d/azure-pipelines.yml#L43

**Comment by baconpaul** [comment]
And for a while I had surge at least cross compiling the test harness linux arm (but none of the ui and we didn’t run it). That’s here https://github.com/surge-synthesizer/surge/blob/5270cfb97a51570f81f29c1e641c0c6def901448/azure-pipelines.yml#L195

we turned thst off when mac arm turned on since thst also exercised our arm build pathway but it may be a good start

I never could figure out how to cross compile the entire ui though and that was pre juce

**Comment by probonopd** [comment]
Look at my currently running GitHub Action, it seems like we are deep into a build...

**Comment by baconpaul** [comment]
Yeah but I don’t want to rework our entire ci pipeline onto actions; can we do equivalent in raw azure?

**Comment by probonopd** [comment]
I don't know. Never used it. (Doesn't it cost money?)

**Comment by probonopd** [comment]
`[100%] Built target stochas_Standalone` - so I think this shows that in principle it is working... even though I still have some bug in there, eventually causing an error.

**Comment by baconpaul** [comment]
No it’s free for open source projects and we use it across our properties
But it just runs unconstrained bash.
Is your action running on a pi or on an x86? If we know how to build on an x86 we can just do thst!

**Comment by probonopd** [comment]
I _think_ that GitHub Actions runs Docker containers for arm/aarch64 on arm/aarch64 hosts, but not 100% sure.

**Comment by baconpaul** [comment]
Yeah so if we have a docker run to build we can run thst in pipeline 
Or if we have a series of toolchain modifications to cross compile we can do that too
That’s basically what we need to build with the infra we use here

**Comment by probonopd** [comment]
It worked! We now have `stochas-1.3.5.5bf2d62-linux-aarch64.tgz` :100: 
https://github.com/probonopd/stochas/suites/5393041259/artifacts/169869579

**Comment by probonopd** [comment]
The standalone version runs on the Raspberry Pi 4 (but I hear no sound other than the test sound).

The plugin is **not** showing up in REAPER (although REAPER has found it in the vst3 path).

**Comment by baconpaul** [comment]
Neat

The plugin doesn’t make sound so that makes sense.

any log messages in reaper?

**Comment by baconpaul** [comment]
Oh also is the sub arch in the vst bundle correctly named?

**Comment by probonopd** [comment]
> any log messages in reaper?

No... (where should they appear?)

**Comment by probonopd** [comment]
> Oh also is the sub arch in the vst bundle correctly named?

`Stochas.vst3/Contents/arm64-linux/Stochas.so`

**Comment by baconpaul** [comment]
I think that maybe should be aarch64 - what does uname say on your pi?

**Comment by baconpaul** [comment]
> > any log messages in reaper?
> 
> No... (where should they appear?)

Stdout maybe?

**Comment by probonopd** [comment]
REAPER Preferences -> Plug-ins -> Re-scan... -> Plug-ins that failed to scan -> /home/pi/.vst3/Stochas.vst3

**Comment by probonopd** [comment]
Might this have to do with it?

https://github.com/leomccormack/SPARTA/issues/22

**Comment by probonopd** [comment]
```
pi@raspberrypi:~ $ ldd ~/.vst3/Stochas.vst3/Contents/arm64-linux/Stochas.so 
	linux-vdso.so.1 (0x0000007f9924b000)
	libfreetype.so.6 => /lib/aarch64-linux-gnu/libfreetype.so.6 (0x0000007f98a0c000)
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f989f8000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f989c7000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f987ef000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f98744000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f98720000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f985aa000)
	libpng16.so.16 => /lib/aarch64-linux-gnu/libpng16.so.16 (0x0000007f98563000)
	libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007f98539000)
	libbrotlidec.so.1 => /lib/aarch64-linux-gnu/libbrotlidec.so.1 (0x0000007f9851e000)
	/lib/ld-linux-aarch64.so.1 (0x0000007f9921b000)
	libbrotlicommon.so.1 => /lib/aarch64-linux-gnu/libbrotlicommon.so.1 (0x0000007f984ed000)
```

**Comment by baconpaul** [comment]
> Might this have to do with it?
> 
> [leomccormack/SPARTA#22](https://github.com/leomccormack/SPARTA/issues/22)

Nah we already set that so we can run in ardour

**Comment by baconpaul** [comment]
> 

Right
So rename the dir inside stochas.vst3 from armbla-Linux to aarch64-Linux

your build is giving it the wrong uname probably because your container doesn’t return that uname quite right

if that mv and rescan works then that’s good!

**Comment by baconpaul** [comment]
Poking around a bit

https://hub.docker.com/r/rycus86/arm64v8-debian-qemu

there’s one of several aarch64 docker qemu images which will run an emulate rpi on x86

**Comment by hfiguiere** [comment]
> `pi@raspberrypi:~ $ ldd ~/.vst3/Stochas.vst3/Contents/arm64-linux/Stochas.so `

This should be `aarch64-linux`, not `arm64-linux`.

From https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Locations+Format/Plugin+Format.html#for-the-linux-platform
> with XXX the architecture name based on the output of command-line "uname -m" (machine hardware) + "-linux" 


And on a RaspberryPi 4 with 64-bits OS
```
$ uname -m
aarch64
```

**Comment by hfiguiere** [comment]
Just to clarify, it's a bug in JUCE. See https://github.com/juce-framework/JUCE/issues/819

It has been fixed since,but 1.3.5 still use that version.

(I have added a fix in the flatpak so it works on aarch64)

**Comment by baconpaul** [comment]
Oh we should just update the stochas juce version to 6.1.6 at least!

I was going to do a bit of stochas TLC sometime this month (including improving the resize behavior and activating the clap and upgrading the mac installer to be signed). Can do same at that moment!

**Comment by rudeog** [comment]
Paul, that would be great! Maybe we could also cut a new release build
after that.

**Comment by baconpaul** [comment]
Yeah I think so! I put a list together in the linked issue of little things but we should also scan the open items here!

**Comment by baconpaul** [comment]
I just pushed an upgrade to JUCE 6.1.6 which will fix this so closing.

**Comment by benkuper** [comment]
> It worked! We now have `stochas-1.3.5.5bf2d62-linux-aarch64.tgz` 💯 https://github.com/probonopd/stochas/suites/5393041259/artifacts/169869579

Hey, digging an old topic, and seems fantastic, but the artifact is expired.. is there a way to post it somewhere stable ?

Thank you, love the work !!
