### ISSUE TITLE
Some Stochas TLC

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/stochas#116]
Just a bit of a refresh

- [ ] Make the UI scaling code more in line with modern juce and dragging and self resizing rather than the store/restart stuff
- [x] JUCE 6.1.6 (see #104)
- [x] Build CLAP
- [x] Upgrade macOS to signed package using sst-plugininfra installer method
- [ ] Skim the other issues to see if anything else can get swept in
- [x] Windows Installer upgrade nad pipeline cleanup

**Comment by windowsrefund** [comment]
#103 seems like low-hanging fruit as well.

**Comment by baconpaul** [comment]
#93 and ship a few themes with the binary also makes sense I bet

**Comment by baconpaul** [comment]
I'm just gonna close this as mostly done.
