### ISSUE TITLE
Notes with a 0% probability are played from time to time

### ISSUE THREAD

**Issue by maxigaz** [surge-synthesizer/stochas#118]
I have a chain of notes where the first note has a probability of 33% and I want the rest to be played only if the first one is played.

I set the probability of all but the first notes to 0% in Poly mode and chained every one of them with the first one individually.

![stochas-2022-08-17_23-01-12](https://user-images.githubusercontent.com/10419911/185242351-112dbdd6-bb9a-4e76-8ee0-e88c6758c723.png)

![stochas-2022-08-17_22-44-36](https://user-images.githubusercontent.com/10419911/185241278-73c30c89-acc0-45f5-9571-d6ce50157021.png)

The problem is that some of the notes with 0% are sometimes played even when the first one is not played.

I have this in Stochas VST3 v1.3.5, in Carla v2.5.0 under Arch Linux.

**Comment by rudeog** [comment]
Thanks for finding this. I have managed to rep this on Windows without the chaining in place, so I don't think its related to the chaining. This might make it easier to find the problem.
