### ISSUE TITLE
Note Lengths

### ISSUE THREAD

**Issue by Ed66uk** [surge-synthesizer/stochas#120]
I am trying to set up Stochas Sequencer to produce random notes 1 bar long. I have dragged the notes out to fill the pattern set the Note-On lengthe = 100, length variance = 0, 

![Note Lengths](https://user-images.githubusercontent.com/111615304/185716927-a72b6153-002a-4fab-8eb8-2560e36153c7.png)

but when I run the sequencer the note lengths vary.
![Note Length Output](https://user-images.githubusercontent.com/111615304/185716941-30cc22cc-41c6-494b-ab66-54bc2a1579fd.png)

What am I dooing wrong?

**Comment by rudeog** [comment]
Can you go under patch options and save your patch to a file and make it available?

**Comment by Ed66uk** [comment]
Thank you for the swift response. I foolishly did not save the project, but here I have tried to recreate it.

I am attaching the Stochas patch and a copy of the midi output from the patch. I cannot upload the patch file as a stocjas patch file, but I have uploaded it as a zip file.

[Test Note Length Patch.zip](https://github.com/surge-synthesizer/stochas/files/9386967/Test.Note.Length.Patch.zip)

Below is a copy of the midi output

[Test_Note_Length_midi_output.zip](https://github.com/surge-synthesizer/stochas/files/9386968/Test_Note_Length_midi_output.zip)

**Comment by Ed66uk** [comment]
Andre.


Thank you for the swift response. I foolishly did not save the project, but here I have tried to recreate it.

I am attaching the Stochas patch and a copy of the midi output from the patch.

**Comment by rudeog** [comment]
I tried your patch in Stochas in my host (Reaper) and it works fine for me. What host are you using? It definitely is acting like that length variance has been set. The length variance is one of the automatable parameters, I am wondering whether its somehow receiving that parameter from the host.

**Comment by Ed66uk** [comment]
I am using Ableton Live 11 Standard on Windows 10.

You are correct, Ihave just tried on Reaper, and npw it is another reason to buy Reaper.

I am coming to the conclusion that Ableton is just not good at handling midi.

Thanks for all your help.
