### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by crshrprt** [surge-synthesizer/stochas#123]
Linux build fails unless this commit in JUCE is used: https://github.com/juce-framework/JUCE/commit/ce8aff22c31c4d932a8414bc6f6185381dc970db

**Comment by baconpaul** [comment]
Ha yeah amazingly I reported this in the juce forums forever ago https://forum.juce.com/t/missing-header-in-juce-componentpeer/51665 but we didn’t pull stochas to 702 yet

**Comment by baconpaul** [comment]
We just now pulled stocks to Juce 7.0.10 so closing this issue
