### ISSUE TITLE
Stochas MIDI input not being recorded

### ISSUE THREAD

**Issue by ALE22-0fficial** [surge-synthesizer/stochas#128]
OS: Mac OS X 10.13.6 High Sierra

Logic Pro X version: 10.4.1

Stochas version: 1.3.9.HEAD.8d9ff47

Issue: MIDI Data does not get recorded by Logic Pro X. The synth plays and it works, but the DAW does not get the MIDI Data that the synth receives, thus making it impossible to record the audio.

Furthermore, when i use the Load Patch function, the Pause button just disappears, making it impossible to turn off, not even by quitting.

Please help.

**Comment by baconpaul** [comment]
To the best of my knowledge to do that in logic you send the midi out to IAC on an external instrument from stochas then bring it back in to your track and it is recordable.

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjhq6KLo_L5AhXHrIkEHXdTBDEQFnoECAsQAw&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-JOZCITL-Og&usg=AOvVaw13TwjNm6Lh0eIR3rT904J5

**Comment by ALE22-0fficial** [comment]
> Hi, can you clarify this a bit. When you say 'the synth' do you mean Stochas, or the synth that you are controlling with Stochas? Also I assume you are referring to the plugin version? or are you talking about the standalone version?


I'm Sorry for not being clear:

When i Say "the synth" i mean the Virtual Instrument that Stochas would control, and i'm talking about the plugin version that goes into the "MIDI FX" section in Logic Pro X, the stand-alone version seems to work fine, but it's a pain to switch back and forth from Logic to the Sequencer.

I tried It with both Chtulhu and a Stock Apple Synth, and with both It did not work.

**Comment by ALE22-0fficial** [comment]
> To the best of my knowledge to do that in logic you send the midi out to IAC on an external instrument from stochas then bring it back in to your track and it is recordable.
> 
> https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjhq6KLo_L5AhXHrIkEHXdTBDEQFnoECAsQAw&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-JOZCITL-Og&usg=AOvVaw13TwjNm6Lh0eIR3rT904J5

Thanks for the advice, i will try It out and let you know!

**Comment by ALE22-0fficial** [comment]
> To the best of my knowledge to do that in logic you send the midi out to IAC on an external instrument from stochas then bring it back in to your track and it is recordable.
> 
> https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjhq6KLo_L5AhXHrIkEHXdTBDEQFnoECAsQAw&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-JOZCITL-Og&usg=AOvVaw13TwjNm6Lh0eIR3rT904J5

Yeah, it kind of worked, but i was wondering if there was an easier way to do it, since i would like to be able to repeat it for multiple audio tracks and i would like for them to not interfere with one another

**Comment by baconpaul** [comment]
I don’t think so. I haven’t been able to figure it out with any logic midi plugin other than that approach at least

**Comment by ALE22-0fficial** [comment]
> I don’t think so. I haven’t been able to figure it out with any logic midi plugin other than that approach at least

Oh, ok!

If (as an example) i tried to run multiple instances of this workaround in the same project, would they conflict? or am i safe that there would be no input overlapping? (e.g, playing multiple Stochas tracks together  for both drums and synth)

**Comment by baconpaul** [comment]
So for playback toh don’t need this just for recording 

for playback stochas will run and output midi just fine 

but yeah if you are routing to record you need channel or driver separation almost definitely 

(the problem I think is that midi fx are designed as effects not as generators - but it’s been since earlier in 10.7 that I looked closely - the above is from an answer I gave someone 8 months ago!)

**Comment by ALE22-0fficial** [comment]
> So for playback toh don’t need this just for recording
> 
> for playback stochas will run and output midi just fine
> 
> but yeah if you are routing to record you need channel or driver separation almost definitely
> 
> (the problem I think is that midi fx are designed as effects not as generators - but it’s been since earlier in 10.7 that I looked closely - the above is from an answer I gave someone 8 months ago!)

So basically i need to create a sh*t-ton of midi bus in the IAC Driver in the laptop? Does it affect things like performance and similar funny stuff?

**Comment by baconpaul** [comment]
You can use 16 channels per. Or render one track midi at a time 

remember you don’t need to do any of this to use stochas in logic. Just if you want to record the midi output as midi. If you bounce to audio or even freeze the track it should work fine.

**Comment by ALE22-0fficial** [comment]
> You can use 16 channels per. Or render one track midi at a time
> 
> remember you don’t need to do any of this to use stochas in logic. Just if you want to record the midi output as midi. If you bounce to audio or even freeze the track it should work fine.

Ok, cool, very cool

i'm a total noob to logic, i moved to it from garageband less than a month ago, so i don't actually know how to bounce to audio, and just using it as-is, as a midi FX does not record anything in the DAW. It may be a problem of the outdated program, but i have an old pc with no support for x64-x86 apps i can't update to a newer version, so i will look into it and see what i can do

**Comment by baconpaul** [comment]
Ahh ok sorry 

so if you are a logic new yser, then

1) just use stochas with a synth downstream and when you press play it will work! There really is no need to record the midi in most use cases.
2) once you are happy with it choose "File / Bounce track in Place" and it will render to audio or
3) enable freeze (do "help/freeze tracks in logic pro" to learn how) and it will basically render a static version for you

**Comment by ALE22-0fficial** [comment]
> Ahh ok sorry
> 
> so if you are a logic new yser, then
> 
> 1. just use stochas with a synth downstream and when you press play it will work! There really is no need to record the midi in most use cases.
> 2. once you are happy with it choose "File / Bounce track in Place" and it will render to audio or
> 3. enable freeze (do "help/freeze tracks in logic pro" to learn how) and it will basically render a static version for you

I tried to use it like this:
![Schermata 2023-04-26 alle 16 46 08](https://user-images.githubusercontent.com/79526988/234613186-cc695fd2-faed-48cb-91b4-5f196b394a49.png)

Programmed the sequencer and all the funny bits

but when i hit "Record" i could hear the sounds playing, but nothing appeared in the timeline, even when i stopped the rec (Logic can be laggy but idgaf, got only 8gb of ram)

this is the problem i tried to explain

the side effect of having the detailed midi is just a happy accident

**Comment by ALE22-0fficial** [comment]
> yeah that's right. when you hit record nothing appears in the timeline.
> 
> Why is that a problem though?

because i have no audio recorded to work with 😅 like, it does not create an actual audio region, it's just monitoring

**Comment by baconpaul** [comment]
right so I think you may need to spend a bit of time with some logic tutorials. Logic doesn't make this super easy. But do this

1. Add a stochas and a surge or alchemy or what not to a track and put a sequence in stochas. If you press play you hear it
2. On that track using the pencil tool draw in a midi region. That midi region will contain nothing. Press play on the region and you hear it still
3. select the track do file/bounce/region to track or some such
and you will get a new audio track with the rendered output of the synth

If you want the raw midi though you need to do the IAC thing above

But this really isn't anything to do with stochas. This is just how midi fx work in logic.

**Comment by baconpaul** [comment]
ahh but duh i told you i should have checked the upgrades

In LPX 10.7.7 there's a new feature which does this internal routing directly.

<img width="547" alt="Screen Shot 2023-04-26 at 11 45 24 AM" src="https://user-images.githubusercontent.com/13387561/234629944-26e41a89-b150-4d85-9d4c-40e1859cd557.png">

so i just put in a stochas and chose that 'record midi here' and pressed record and got the midi out. basically it wires up the internal routing for you directly.

So in the months between that original advice and today, that works

Anyway so there's the 9 ways I think you can solve this!
