### ISSUE TITLE
extras files and folders in the nightly release archives

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/stochas#13]
verified in the archive `stochas-e2a0b39-linux-x86_64.tgz`

in addition to `VST3` and `Standalone` folders it contains at the top level the file `libStochas_SharedCode.a ` and a `JuceLibraryCode` folder containing the files
```
Defs.txt
Info.txt
JuceHeader.h
```
these could likely be removed

also, would it be possible to have a folder named Stochas as the parent folder with the `VST3` and `Standalone` folders as sub-directories?

**Comment by baconpaul** [comment]
Yeah we are fixing up the installer images one by one. Gotta deslop Linux! Will get to it this week.
