### ISSUE TITLE
FL Studio, speed button also divides pattern length

### ISSUE THREAD

**Issue by dariotortola** [surge-synthesizer/stochas#131]
When I use a Playback speed above 1 Stochas works as expected (eg, with 16 total steps, 16 steps per measure, speed 2, Stochas passes twice through the grid) but when it is less than one, it also divides the grid. When speed is 1/2, I expected each Stochas' step to last for twice as long, but to play all steps. Instead, each step lasts indeed twice as long, but only half the steps are used.
I've tried changing the Total Steps and the Steps per Measure but the result is still not just that speed is half, but the pattern length is halved as well.
With speed 1/4, 1/8 and 1/16 it happens the same, changing only the part of the pattern Stochas ignores.

**Comment by baconpaul** [comment]
just a wild guess. If rather than FL time signature of 4/4 with 1/2 time you do 8/4 with 1/2 time does it work? (Can you even do that in FL? I assume so).

I wonder if stochas is using measure start or beats into measure somewhere and not compensating for sub-integer traversals?

**Comment by rudeog** [comment]
Another thing is that Stochas uses the position info to determine which step to play. So for example if you are looping an area of 1 bar and you are playing at half speed, it will jump back to the beginning when it loops, even though its only played 8 steps.

**Comment by dariotortola** [comment]
@baconpaul Using 8/4 in FL Studio still doesn't work, having speed 1/2 makes Stochas use half its grid.
@rudeog hit it. If I loop a 2 bar pattern in song mode then it reaches the end of the grid. It doesn't if I do it in pattern mode

**Comment by baconpaul** [comment]
glad it is resolved!
