### ISSUE TITLE
How to open stochas on MacBook Pro 2020?

### ISSUE THREAD

**Issue by Eriotica** [surge-synthesizer/stochas#132]
Hi ya'all, sorry new to this, but I get warning on "''Stochas.pkg' cannot be opened because it is from an unidentified developer"

And when I try to open the other "Stochas-1.3.9.-mac.dmg" download I get "'Stochas' can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."

Using latest Chrome on a 2020 MacBook Pro.

I tried to override it by trying to open it in Finder but it didn't work.

What's the best way to get it to open?

Thank you very much!

**Comment by baconpaul** [comment]
oh i really need to modify the installers to sign it like the others.

you can shift or right click to pick open on the dmg and install, then do https://www.youtube.com/watch?v=AHoTH-OWGnA

but we sign everything else. I should just rewrite the stochas installer to sign this too

**Comment by Eriotica** [comment]
Thank you so much Paul! ✨🌙❤️🌙✨

**Comment by baconpaul** [comment]
I know its been a while!

As of 1.3.11 / Nightly release, we are now signing the mac installer which should stop the problems with mac installation

**Comment by Eriotica** [comment]
Wonderful! Thank you kindly!
