### ISSUE TITLE
Cannot Open The AU or VST In Ableton 9.7 On Mac High Sierra

### ISSUE THREAD

**Issue by midnightstepper** [surge-synthesizer/stochas#135]
Hi there

As stated above I'm having trouble with this, Stochas does not show up in the plug-in folders after installation. I've tried an earlier version but still no joy.

Any ideas?

Many thanks in advance.

**Comment by baconpaul** [comment]
Well the VST definitely won't work; we have a VST3 and that old a version of live only supports VST2

I am not sure why the AU doesn't work but I do see comments in the codebase about AU and midi processing in that vintage of DAW being difficult to configure.

So I really think the problem amounts to using a 7 year old version of live. I'm not sure what we could do to debug it?

One thing to try - does b-step (https://github.com/surge-synthesizer/b-step/releases/tag/Nightly) AU work in your live? If it does I could scan the configuration differences between the two bits of software. But I suspect it might not.

**Comment by midnightstepper** [comment]
Hi Paul

Many thanks for getting back to me so quickly. I tried B Step and it 
only works as a VST on my machine. You are correct and it's as I 
suspected, just down to my archaic version of Live. That involves a 
whole new machine for me, which I'm not in the market for right now.

Hey ho, I'll just have to enjoy Stochas from afar for now.

Thank you again.

Regards

Neville

On 03/09/2023 17:23, Paul wrote:

> Well the VST definitely won't work; we have a VST3 and that old a 
> version of live only supports VST2
> 
> I am not sure why the AU doesn't work but I do see comments in the 
> codebase about AU and midi processing in that vintage of DAW being 
> difficult to configure.
> 
> So I really think the problem amounts to using a 7 year old version of 
> live. I'm not sure what we could do to debug it?
> 
> One thing to try - does b-step 
> (https://github.com/surge-synthesizer/b-step/releases/tag/Nightly) AU 
> work in your live? If it does I could scan the configuration 
> differences between the two bits of software. But I suspect it might 
> not.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>

-- 
Neville Watson
https://www.facebook.com/nevillecwatson/
https://soundcloud.com/nevillewatson

Links:
------
[1] 
https://github.com/surge-synthesizer/stochas/issues/135#issuecomment-1704346317
[2]
