### ISSUE TITLE
use the short circuit style mac and win installers

### ISSUE THREAD

**Issue by RustoMCSpit** [surge-synthesizer/stochas#147]

**Comment by baconpaul** [comment]
Doung this will also close #132, is a partial dup of #116 , will partially address #39

**Comment by RustoMCSpit** [comment]
> Doung this will also close #132, is a partial dup of #116 , will partially address #39

is the installer applied in all other surge projects?

**Comment by baconpaul** [comment]
Yes

**Comment by baconpaul** [comment]
(Linux is more annoying because linux doesn’t exist etc but we have a set of scripts to make debs and rpms and zips in surge which we slowly port to other products if they don’t get packaged)
