### ISSUE TITLE
Linux the .clap file is missing?

### ISSUE THREAD

**Issue by CodesoundR** [surge-synthesizer/stochas#151]
Hi,

I downloaded the Linux version of Stochas but I can't find the .clap version (if it exists)

[[img]https://i.imgur.com/Xsmm5SK.png[/img]](https://imgur.com/Xsmm5SK)

cheers

**Comment by baconpaul** [comment]
I need to rewrite the installers and I bet when I do I will find out the clap is just skipped in our pipeline. If you self build it will be there 

rewriting these is high in my list - last step to move everything to actions and also sign it in Mac - so I’ll leave this open until I get to it probably next week

thanks!

**Comment by CodesoundR** [comment]
Hi, thank you so much! I wait for the release..... 


THANKS AGAIN!

cheers

**Comment by baconpaul** [comment]
yes unfortunately it didn't happen last week. Thanks for the ping. I hope to get it before vacation on thursday.

**Comment by baconpaul** [comment]
I’m sorry a couple of problems meant I didn’t get to this before my long eeekend vacation. I will keep it in list for next week. Haven’t forgotten

**Comment by baconpaul** [comment]
OK we finally got this done. The nightly and the 1.3.11 targz should both have a CLAP now. Thanks for your patience.

**Comment by CodesoundR** [comment]
THANK YOU SO MUCH!!! THANKS FOR YOUR WORKS LIKE THIS...
cheers

Il giorno dom 27 ott 2024 alle ore 20:37 Paul ***@***.***> ha
scritto:
