### ISSUE TITLE
Question: Controlling Position Variance via MIDI

### ISSUE THREAD

**Issue by 2nd-Bird** [surge-synthesizer/stochas#154]
Thank you for developing such an excellent sequencer.

I am using Stochas with Cakewalk and controlling various parameters of Stochas through a MIDI controller via Active Controller Technology. I have a question regarding this setup.

Among the parameters displayed in Active Controller Technology, only the Position Variance parameter does not seem to work. Is this by design? Do you have any plans to address this in the future?

I understand that Position Variance is not currently available for MIDI Mapping in Stochas.

**Comment by rudeog** [comment]
Hi, is the Active Controller Technology tied to VST automation parameters? If so, I am not sure why the position variance is not showing up there. If I look at automation targets in Reaper I can control position variance with no problem.
Yeah, its not available for MIDI, but that was because I wasn't sure how used that would be.

**Comment by 2nd-Bird** [comment]
Thank you for your response.

It's good to know that it works without any issues in Reaper.

Active Controller Technology is indeed tied to the VST automation parameters, and Position Variance is displayed in the ACT R5. After further troubleshooting, it turned out to be an issue with the ACT MIDI Controller Preset. Specifically, only R5 in the preset for the AKAI MPK49 [Preset30] was not receiving MIDI controller input. This issue did not occur when using other presets.

**Comment by rudeog** [comment]
Ok, I'm going to leave this issue open as a reminder to add position variance to the midi mappings, as at least one person would use it :-)
