### ISSUE TITLE
Windows Installer 3.12 installs only uninstall

### ISSUE THREAD

**Issue by midiguru23** [surge-synthesizer/stochas#160]
I just now downloaded the Windows installer for 3.12 from the Assets list. Tried it twice, just to be certain. It installs only an uninstaller, not the actual program. I'm in Windows 10, if that makes a difference, but I don't see why it would.

**Comment by rudeog** [comment]
Thanks for reporting this. I guess the win installer has been broke for some time :-(
Should be fixed now in the nightly build

**Comment by baconpaul** [comment]
Oh darn it sorry that was my fault when I moved to the signed pipelines and retired 32 bit a couple of weeks ago. I tested the builds but didn’t realize the new installer didn’t install over the old one properly 

thanks and sorry again

**Comment by rudeog** [comment]
Paul, I see your change now. Thats a relief, i thought it had been broken for a long time.

**Comment by baconpaul** [comment]
There’s a 3.13 up now
