### ISSUE TITLE
Linux build?

### ISSUE THREAD

**Issue by mxmilkiib** [surge-synthesizer/stochas#2]
How much might need to be done to achieve a Linux build?

**Comment by baconpaul** [comment]
It builds and runs on Linux just fine

**Comment by baconpaul** [comment]
Oh but hah we didn’t update the readme

Checkout
Git submodule update —init —recursive
Cmake -Bbuild
Cmake —build build —config Release

Are the commands.

**Comment by baconpaul** [comment]
And we should have a Linux binary coming out of the pipelines this weekend

**Comment by mxmilkiib** [comment]
No, the information is there, I just missed out the submodule phase ;o ;) Got it built now, thanks.

**Comment by baconpaul** [comment]
Awesome! Have fun!
