### ISSUE TITLE
AU plugin could not be validated in Logic Pro X 10.4.8

### ISSUE THREAD

**Issue by Colliwomple** [surge-synthesizer/stochas#23]
When i try to validate it with the plugin manager i get
" validating Audio Unit Stochas by Audio Vitamins:

validation result: Validierung erfolgreich

updating properties of AU Stochas by Audio Vitamins…FAILED! "
When try to opening the plugin i get " Can´t load ..... contact developer"
OSX Version 10.14.5
Tried it with version 1.3.1 and 1.3.2... can`t validate
Edit: just found the new github repo 1.3.3 validated ! Sorry for posting too soon

Would be nice if you can make the GUI resizable !? TIA

**Comment by rudeog** [comment]
Thanks. I saw your other post and responded too soon!
Glad you got it sorted.
