### ISSUE TITLE
prblem loading on Mac running Yosemite

### ISSUE THREAD

**Issue by DKactus** [surge-synthesizer/stochas#24]
Hi, although I run the installer, Reaper can not read the AU and VST files (Mac running Yosemite)

**Comment by rudeog** [comment]
Hi DKactus, 
The oldest mac OS that our build system will build for is El Capitan. We ran into some issues when trying to target SDK earlier than 10.11 (problems building). It's possible that these may be resolved somehow, however we didn't anticipate many users at that version. We might have to revisit this.

**Comment by DKactus** [comment]
ok, thanks for your feedback!
