### ISSUE TITLE
Change vendor name if possible

### ISSUE THREAD

**Issue by rudeog** [surge-synthesizer/stochas#29]
Change vendor name from Audio Vitamins to SST if it doesn't prevent old projects from loading.

**Comment by baconpaul** [comment]
So we found changing the vendor name didn't hurt us as long as we kept the same vendor ID. So we are "Surge Synth Team" / "VmbA" for the surge plugs.

There was a moment where I worried having "Surge Synth Team" with a different vendor ID would break stuff; we should test this. Like if you are "Surge Synth Team / AxvT" or whatever does logic, reaper, etc... find you OK? I think Logic was especially sensitive to this but my memory on this is all fuzzy. And in the end, we just used VmbA for our new plugs also to be safe and lazy :)

**Comment by rudeog** [comment]
Ok, will change vendor name, keep same vendor id.
