### ISSUE TITLE
Not working in FL Studio 12 64bit

### ISSUE THREAD

**Issue by siddytucker79** [surge-synthesizer/stochas#30]
Used the windows installer.  Stochas will not send midi info to any plugin I link it to via the midi port options in the VST Wrapper settings.

**Comment by baconpaul** [comment]
I don't use FL, but there was a long conversation about this in #stochas-development in our discord server this afternoon and how to get it to work with FL's particular midi routing choices. Perhaps that would help immediately while the answer becomes some more permanent documentation? hope that helps.

**Comment by K0rrid0r** [comment]
@siddytucker79 what version of FL studio are you on?

**Comment by siddytucker79** [comment]
I'm on FL Studio 12 and the Windows installer gives me only a VST3 file

**Comment by K0rrid0r** [comment]
Check my longer answer i just did!

**Comment by siddytucker79** [comment]
Sorry.  Still no luck even after following all the steps you provided and double checking to make sure I followed them all correctly

**Comment by K0rrid0r** [comment]
Right!

Well try the builds i did. If you get MidiChannelFilter together with them, it should work. (im currently listening to three layers from one instance of stochas)
[Stochas VST2 and VST3 32 bit.zip](https://github.com/surge-synthesizer/stochas/files/5181174/Stochas.VST2.and.VST3.32.bit.zip)

Please report back how that goes. So we can make the mark on your stochas version + daw.

**Comment by siddytucker79** [comment]
Still no luck sadly

**Comment by K0rrid0r** [comment]
wow really not even with the VST2 i provided?

**Comment by siddytucker79** [comment]
Yep.  Tried both the VST2 and VST3 in conjuction with the midi channel filter.  Still no midi info being sent to the synth

**Comment by K0rrid0r** [comment]
so both those "Stochas" will show up with the same name. can you double check that you used the VST2 and not VST3 and tested around?

![STO6](https://user-images.githubusercontent.com/56724286/92413431-5c832e00-f150-11ea-91af-361cf0cb7760.gif)

**Comment by siddytucker79** [comment]
Yup, just double checked.  Can confirm I used the VST2

**Comment by K0rrid0r** [comment]
what about stochas sending just a port number to a synth? does that work?

**Comment by K0rrid0r** [comment]
well then im out of ideas :( try another daw.

**Comment by K0rrid0r** [comment]
i can make these specific files work just fine in FL 10 and FL 20.6

**Comment by siddytucker79** [comment]
All good my dude.  I appreciate you taking all this time to try and help me

**Comment by siddytucker79** [comment]
Do you have a link to the discord server baconpaul was referring to?

**Comment by K0rrid0r** [comment]
https://discord.com/channels/703345273992118413/703345273992118416

**Comment by eamonbohan** [comment]
> @siddytucker79 what version of FL studio are you on? Did you use stochas VST3 or VST2? and what bit version 32/64 bit?
> 
> Why I'm asking is because i figured out today how to set this up.
> 
> Myself i use FL Studio 10 and VST2 32 bit version of stochas that i built from the code provided.
> In FL 10 the VST3 stochas exhibits exactly the problem you describe. But in FL 20 the VST3 works fine. (i did try with a VST3 32 bit version, maybe actually there is a problem with the 64 bit)
>
> That is one way of getting each layer to work with -one- stochas in FL.

Hi @K0rrid0r,

Thanks for outlining these comprehensive instructions for trying to make MIDI routing work on FL Studio v.10 with the 32-bit VST2 dll file for Stochas.

Could you point to the VST2 file you are using?

In the [repo's releases page](https://github.com/surge-synthesizer/stochas/releases), it seems that both `stochas-1.3.3.-win.zip` and `stochas_windows_installer.exe` only include the VST3, (in x86 and x64 bits, out of which, I assume we rule out x64 and use x86). Same for the official [releases page](https://github.com/surge-synthesizer/stochas/releases).

Thanks,

**Comment by K0rrid0r** [comment]
@eamonbohan check this zip in this post. the .dll is a VST2 that im currently listening to (with several layers from one stochas, using that exact method)

I only posted it to help with troubleshooting here. Nothing seems to work for @siddytucker79 thought.

https://github.com/surge-synthesizer/stochas/issues/30#issuecomment-688044210

**Comment by siddytucker79** [comment]
So I've discovered that stochas works fine for me in the 32bit version of my FL but not the 64bit version (which I mainly use)

**Comment by eamonbohan** [comment]
@K0rrid0r got it--it seems that 32 bit VST2 dll works in FL 20.

**Comment by K0rrid0r** [comment]
@siddytucker79 can you be more specific? i provided two 32 bit stochas. which one are you referring too?

@eamonbohan Great! Neat!

**Comment by siddytucker79** [comment]
> @siddytucker79 can you be more specific? i provided two 32 bit stochas. which one are you referring too?
> 
Sorry I meant the 32 bit version of FL Studio 12 not the 32 bit version of stochas

**Comment by K0rrid0r** [comment]
@siddytucker79 yeah those things gotta be correct otherwise it wont work :) so did the The Midi Channel Filter work then?

and i bet if i send a VST2 64 bit it will work in that version as well.

**Comment by K0rrid0r** [comment]
So can you also check if the VST3 32 bit now work in your correctly opened FL studio 12 32 bit?

**Comment by siddytucker79** [comment]
> @siddytucker79 yeah those things gotta be correct otherwise it wont work :) so did the The Midi Channel Filter work then?
> 
> and i bet if i send a VST2 64 bit it will work in that version as well.

Lmao forgive my uh ~cognitive impairment~

**Comment by siddytucker79** [comment]
> @siddytucker79
> So can you also check if the VST3 32 bit now work in your correctly opened FL studio 12 32 bit?
> 
> Do a simple port out (stochas) to port in (synth) test

Yeah sorry I should be more specific.  That's what I did and it worked flawlessly.

**Comment by siddytucker79** [comment]
> @siddytucker79
> So can you also check if the VST3 32 bit now work in your correctly opened FL studio 12 32 bit?
> 
> Do a simple port out (stochas) to port in (synth) test

VST3 32bit doesn't work for some reason

**Comment by K0rrid0r** [comment]
in FL 12 32 Bit?

**Comment by siddytucker79** [comment]
Yup

**Comment by K0rrid0r** [comment]
Right! The VST3 32 Bit don't work in FL 10 either, hence i use the VST2 32 Bit (because i don't want to change daw) But the VST3 32 bit does work in FL 20 32 bit. I don't know what happend there in between.

Now you know. You can use the VST2 32 bit and i can send you a VST2 64 bit later.

Good info to know for the stochas dev.

**Comment by siddytucker79** [comment]
Awesome.  Thanks for you patience dealing with me lol

**Comment by K0rrid0r** [comment]
and writing on github here when you have a problem helps if you are super specific about every move you do and change otherwise we end up with 100 comments.

**Comment by K0rrid0r** [comment]
@siddytucker79 there you go, if that's your only alternative
[Stochas-vst2-64bit.zip](https://github.com/surge-synthesizer/stochas/files/5187019/Stochas-vst2-64bit.zip)

**Comment by rudeog** [comment]
@K0rrid0r it sounds like we definitely need VST2 builds?

**Comment by K0rrid0r** [comment]
Yeah well that is up to you and Paul i guess. I'm merely trying to find out what is causing the problems and where Stochas works and where it dosen't, at least on the FL side of things :)
