### ISSUE TITLE
is this 32 or 64 bit ? 

### ISSUE THREAD

**Issue by dnl13** [surge-synthesizer/stochas#31]
Hi folks,
sorry that I have to report this as a problem. But I can't find any information about whether it is 32bit or 64bit? I am running a version of Ableton Live 9 64bit and can't find the plugin in the list. If it is 32bit it is clear why :) 
Maybe you could put a note on the homepage and in the readme file? 
Greetings  

edit: on macOS 10.13.6 - Ableton Live Suite 9 (9.7.7 64Bit)

**Comment by baconpaul** [comment]
64 bit vst3. Live9 lacks vst3 support if I recall.

**Comment by dnl13** [comment]
hm, 
but the *.component should appear i guess ?!?

**Comment by baconpaul** [comment]
Oh didn’t see you were mac 

It should if live9 supports midi out au.

**Comment by dnl13** [comment]
I have seen a tutorial on stochas using ableton live 9, 
but i do not know if its 32 or 64 bit version. 

update: 
anyway i have both versions installed and the plugin does not appear in any version.
maybe it is the os ? 
and yep, i double checked if i had put them in the right directory  =)

**Comment by baconpaul** [comment]
Right; then we will have to wait for @rudeog - I don't know enough about live9 to guess.

Anything in the logs?

**Comment by K0rrid0r** [comment]
![STO5](https://user-images.githubusercontent.com/56724286/92388018-d8f91b00-f116-11ea-9792-64845128e323.gif)
@dnl13 which one did you install?

this was the installer from https://surge-synth-team.org/stochas/

**Comment by K0rrid0r** [comment]
here it says 64 bit 
https://www.kvraudio.com/product/stochas-by-audio-vitamins

**Comment by dnl13** [comment]
Hey @K0rrid0r 
I'm on macOS and sadly their is no installer.
First I tryed the on by kvraudio which comes with .pkg but same result, no Plugins listed in AL9. 

but then i downloaded 1.3.3 from this repo 
So this .dmg comes with 3 Files: 
Stochas.app ( which works) 
Stochas.component 
Stochas.vst 

Which i have put to /Library/Audio/Audio Plugins/
.component to Component Folder and .vst3 to VST3 Folder 

I also tryed Adobe Audition and rescanned my Plugins Folder. 
Also, everything else is present but Stochas is missing.

So maybe an OS related issue ?!?

**Comment by rudeog** [comment]
Hi,
Currently we are building 64 bit VST3 and AU on Mac. I know that in the Audio Vitamins days we built VST2 but can't remember whether that was on the mac (as well as windows). I found this on the Ableton site:
Live Versions: 9-10
Operating System: All
**Supported Plug-in formats**
VST2 - 64 & 32-bit
VST3 - 64-bit (Live 10.1 and later only)
Audio Unit 2 (AU) - 64 & 32-bit
**Unsupported Plug-in formats**
Audio Unit 3
Audio Unit 1 (since Live 9.2)
Direct X
AAX
RTAS

So the question is, are we building AU v2 or AU v3. @baconpaul, do you know?

**Comment by rudeog** [comment]
It looks like we are not building AUv3 (there are two options in JUCE AU and AUv3) so I assume we are AU v2 but not 100% certain. Either way, it seems like you should be able to pick up the AU version.
Are you able to use any other AU plugins in your version of Live?
It might be worth throwing the VST2 build back in on Win and Mac to see if it helps (would need to track down the Mac VST2 SDK though)

**Comment by dnl13** [comment]
I have "Surge Synth Team" > "Surge" and "SurgeEffectsBank" up and running as AudioUnit and a lot of different other plugins as well e.g.Spitfire Audio, Native Instruments etc. etc.
And Stocha is the only Plugin not showing up 
I tried to build it on my own with XCode after downloading the linked JUCE lib and had to cancel the 
```
if( Git_FOUND )
```
part because my git is somehow messed up. 

It finishes building and i copy from 
```
stochas-main/build/stochas_artefacts/Release/AU/Stochas.component
```
to my Plugin Folder but still not showing.

I then tried the "Stochas.xcodeproj"
and found in: 

 stochas > stochas > stochas_AU > CMakeLists.txt

this part in Line 88: 

```
FORMATS VST3 ${VST2} AU Standalone     # The formats to build. Other valid formats are: AAX Unity VST AU AUv3
```

I don't know if this helps

**Comment by rudeog** [comment]
You might try playing with the IS_SYNTH and IS_MIDI_EFFECT. We had to set them one way for Logic, but might have adverse affect in this situation.

**Comment by dnl13** [comment]
ok i tried: 
```
STOCHAS_IS_SYNTH "TRUE"
STOCHAS_IS_MIDI_EFFECT "FALSE"
```
now it shows up as 
```
Audio Vitamines > Stochas 
```
but as audio effect like some chorus/ flanger e.g. awaiting audio to be passed in 

i will try to put synth FALSE and MIDI_EFFECT TRUE 
maybe i can get it to work how it should be, 
otherwise i could use the standalone app with IAC-Driver 

but hey, finaly it reveals it self in the audio unit plugins page ;)

**Comment by dnl13** [comment]
Ok this:
```
STOCHAS_IS_MIDI_EFFECT "TRUE"
```
hides the Plugin everytime. It does not matter if IS_SYNT is true or not or even CATEGORY is Instrument or Effect if IS_MIDI_EFFECT "TRUE" it disappears. 


but i came across this link 
[https://forum.juce.com/t/midi-effect-for-ableton/32455/12](https://forum.juce.com/t/midi-effect-for-ableton/32455/12)

and it seams that i am out of luck without a newer version of Ableton and VST3 support 
so i think i have to do the workaround with the IAC-Driver 

but anyway - thank you everyone !!!
I guess this issue can be closed :(

**Comment by baconpaul** [comment]
Yeah sorry. I'm not a live user but it seems famous for having different routing than other tools, especially the older versions.
