### ISSUE TITLE
Windows installer not working

### ISSUE THREAD

**Issue by ZwergNaseXXL** [surge-synthesizer/stochas#33]
- I downloaded the Windows installer exe from here and ran it. 
- Windows protection gimmick asked me if I want to run this software from an unknown source -> yes. 
- I'm on a non-admin account, installer requires admin rights for unknown reasons (issue # 1) -> yes, enter admin password.
- Installer starts, asks me to accept license -> yes.
- Installler asks me to choose between 32 and 64 bit VSTs -> 64.
- Installer says done, but it has never asked me WHERE I want to install to (issue # 2).
- I start looking for the installed VST. There's an empty folder named "stochas" right next to the installer. Nothing in my usual VST folders, the standard VST folder, the program files folders, the program data folder, my user/appdata folders, nor in the admin/appdata folders. Only this one empty folder. (issue # 3)

FYI, the installation was registered with Windows, so there is an uninstall option in "add or remove programs".

I ended up downloading the zip instead and just copied the vst3 and exe files to my preferred locations. No admin rights required. :)

Expected behavior:
- Installer offers a location option.
- Installer offers the stand-alone installation.
- The relevant files are actually installed to their locations.
- Don't require admin rights unless the chosen locations actually require them.

**Comment by rudeog** [comment]
It should put the VST3 into the standard VST3 folder can you check to see whether it ended up there? 
On Windows this is c:\program files\common files\VST3 for 64 bit and c:\program files (x86)\common files\VST3 for x86
These are standard VST3 locations which should be recognized by all DAWs. For VST2 the location was more important, but afaik a daw has to look at these vst3 locations at a minimum.

**Comment by ZwergNaseXXL** [comment]
Thanks, you're right, I missed those "common files" folders. Stochas did end up in C:\Program Files\Common Files\VST3. I also have the "Use system VST3 folder" setting in Ableton off, so Ableton didn't find Stochas until I copied it to my custom VST3 folder.

Anyway, I think my other points are still valid.
