### ISSUE TITLE
Install appears to end without actually installing Window 10

### ISSUE THREAD

**Issue by geneblandjr** [surge-synthesizer/stochas#37]
After downloading the stochas Windows installer, I launch it and it starts.  It prompts me to agree to the open source license and then never asks where I want to install the dll (my vst folders are somewhat different than "standard").  Then it launches the installers, appears to complete about 1/3 of the progress bar, exists and shows me a dialog indicating that it has successfully installed stochas.  If it created the stochas.dll, I have no idea where it put it (I've looked in all the obvious places).  It did put a VST3 file on the machine and did create an uninstall process....  I tried this with both the 64 bit (desired) and the 32 bit (not desired) options, and both did the same thing.  

I tried downloading the .zip file and extracting it, but there are no instructions of how to install from the zip.  There are no DLLs in the zip, so perhaps this works differently from what I expect.  

This may not be a bug as such == other than the fact that the operation of the installer does not follow the description on the website, and may not be working.

**Comment by geneblandjr** [comment]
A few technical details of where I'm seeing this:
Windows 10 Pro
Version 1909
Build  18363.1016
16 GB Memory
Let me know if you need more....
-Gene

**Comment by rudeog** [comment]
Gene, two things:
1. Try to get the latest developer release. It will ask to provide a path for the VST3 folder. This should be a standard folder though for VST3.
2. There is no stochas.dll, only a stochas.vst3. We are not currently building VST2 due to license incompatibilities with GPL. As such your DAW will need to support VST3. The source does offer full support for VST2 though, so if you have the VST2 you should be able to turn on and build that.

**Comment by geneblandjr** [comment]
Okay, so now I feel a bit silly.  Honestly, I had not noticed that VST3 plugins have a new home.  I'm using Ableton Live 10, so no issue with VST3....other than my VST3 option was set to the wrong folder (also my fault).  All fixed now and I'm looking forward to digging into your product.  

By the way, the User Guide still mentions DLL files in the Installation chapter, so you may wish to remove that bit if you're moving away from supporting/distributing VST2.  Might save a bit of confusion. 

Feel free to close this one out.  I really appreciate the quick response!  You can chalk this one up to "issue between user and keyboard".  Your answer back gave me the critical info for me to figure out where I had gone wrong and a quick "Let me Google that for you..." session quickly resolved the issue.

-Gene

**Comment by rudeog** [comment]
No problem Gene, hope you are able to get some use out of Stochas.
