### ISSUE TITLE
VST 2 not available through installer nor zip

### ISSUE THREAD

**Issue by ogauchard** [surge-synthesizer/stochas#40]
Hi,
Stochas VST 2 plugin is not available through the windows installer nor in the zip archive.
Is there any way to get it ?
Thank you.

**Comment by rudeog** [comment]
Hi,
Due to licensing changes made by Steinberg, we can't build the vst2 only the VST3 and AU. However if you have the vst2 sdk available, you can build it by adding -DVST2_PATH=<path> to the build command.

**Comment by ogauchard** [comment]
Ok, thank you for the answer.
I am using Reason and it does not support VST3... 
Is there any way to export in midi using the standalone version ?

**Comment by rudeog** [comment]
On windows you can use a program such as midiyoke or LoopBe (https://www.nerds.de/en/loopbe1.html ) to route midi from standalone version to reason. Bear in mind that stochas standalone does not yet support external clock, and does not yet send start/stop/spp. So in your situation, reason will just be acting as a synth to play the incoming midi notes.

**Comment by ogauchard** [comment]
I will try this !
Thank you for the answer and for supporting this excellent tool.
