### ISSUE TITLE
Stochas crashes Cantabile host when song is loaded

### ISSUE THREAD

**Issue by RobboKocho** [surge-synthesizer/stochas#46]
I can use Stochas when I have added it as plugin in Cantabile, but when I save the Song and load it again, it crashes Cantabile. For testing, there is a free version of Cantabile to download at:
https://www.cantabilesoftware.com/

Thanks

**Comment by rudeog** [comment]
Please try the latest developer release. There was a bug fix for Cantabile the other day. If it's still not working, let us know.

**Comment by RobboKocho** [comment]
Wow, that was quick! The developer release seems to work fine so far.

Thanks a lot!

**Comment by RobboKocho** [comment]
I will run some tests the next days and close the issue when it works.

**Comment by rudeog** [comment]
Thanks, let me know. If it looks fine, I'll promote to a new release.

**Comment by RobboKocho** [comment]
Stochas works fine with Cantabile now!

Thanks!
