### ISSUE TITLE
Linux: VST3 Plugin not recognized and cannot be loaded

### ISSUE THREAD

**Issue by henning** [surge-synthesizer/stochas#47]
I am trying to run Stochas as vst plugin, but neither the prebuilt binary downloaded from here (Version 1.3.3) not when I build it myself it gets recognized and can be used by any vst host. I tried with: Bitwig, Carla, and Tracktion Waveform 11.

The standalone version can be started as expected (besides I cannot yet use it effectively due to the hidpi issue so everything is too small to be useable)

UPDATE:

Summarizing version details:

* The Linux OS version is Ubuntu Focal
* Bitwig version is now 3.3 but it was the same when i tried it with 3.2.8 some weeks ago (other vst3 plugins are displayed and can be loaded, most important surge is working with no problems)
* Waveform version is the (latest)beta version 11.1.25 (other vst3 plugins can be loaded)
* Carla version is 2.1.0 - this actually seems to be generally unable to use vst3, even though the plugin list offers a filter for "vst3"
* Stochas versions tested where all available binaries currently downloadable as well as a self built version from master HEAD as of today

**Comment by baconpaul** [comment]
Which versions of said DAWs?

Bitwig didn't support VST3 linux until about 3.2 (and still has some bugs). Carla is on a branch. And waveform 11 needs the current beta not head to load a VST3.

**Comment by henning** [comment]
Bitwig 3.3 beta 2 (and I also tried with 3.2.8 a few weeks ago, same experience), carla 2.1.0, waveform 11 latest beta.

I actually wasnt aware that vst3 is not fully supported everywhere, but now I verified that in Bitwig and Waveform other vst3 plugins (e.g. Surge) are shown and can be loaded, while Stochas is not displayed in the plugin lists. In Carla (which I dont use normallay just tried to see if with this Stochas can be loaded) it's true, there is a filter option for vst3 but really no vst3 plugins available on the system are recognized, so it's really carlas fault.

Anything else I can try? 
Would it be best if i go building Stochas with vst2 support?
My main goal is being able to use it in Bitwig - i just tried the other hosts as a comparison/verification.

**Comment by rudeog** [comment]
What OS? I'm pretty sure I was able to get it going on Bitwig in Windows with VST3.
If you want to try with VST2 you should be ok. There is one cmake define you need to set to point to your vst2 sdk and it should work.

**Comment by rudeog** [comment]
Another thing you can try is mess with defining STOCHAS_IS_SYNTH and STOCHAS_IS_MIDI_EFFECT (see cmake file)

**Comment by henning** [comment]
Linux - Ubuntu Focal is the OS.

Gonna try these things these days and report back - thank you!

**Comment by henning** [comment]
finally got to check this further... So first of all: it works! ;)

I dont know if it is because recent code changes, or that I needed to find out that for installation, I need to copy the whole Stochas.vst folder structure into my vst3 folder. Having installed only vst2 plugins before I simply don't know that and just copied the .so file... I dont remember if I tried it with the folder too the last time in october, maybe, then it's the recent code changes that made it work. Thanks! 

What was a bit strange: the first two times when I tried it, the plugin kept crashing, but now it seems to work. Thanks.

BTW I also tried to build vst2 before finding the above, but the vst2 sdk isn't available anywhere...

**Comment by baconpaul** [comment]
Are you on BW 33beta1? The bitwig team has been changing lots of linkage things which have helped many a plug work in the latest so that could also be the factor?

**Comment by henning** [comment]
Bitwig 3.3 is realeased and thats what i’m using--
Henning Sprang
http://www.sprang.de

**Comment by henning** [comment]
Ah, and anyway, Surge vst3 did work the whole time - so the solution was likely either the update of the juce platform in Stochas that I saw happened in the course of the hidpi scaling solution, or simply my finally acquired ability to put the right files in the right place...

**Comment by pitrackster** [comment]
Hi ! I also faced the issue (Ubuntu Studio 20.04) Had to copy the whole stochas vst3 folder into my linux vst folder to make it recognized !
thanx for the hint

**Comment by fractalf** [comment]
Same here, been scratching my head for close to an hour now. Thanks @henning ! :)
