### ISSUE TITLE
How do I make Stochas play 

### ISSUE THREAD

**Issue by asafcha** [surge-synthesizer/stochas#61]
Hi, Stochas newbie here and I can't seem to get it to work properly. I set the output midi ch to 1, I opened another vst on the same channel, I can see the white bar moving along the grid on Stochas when I hit Play, and when I add notes to the grid nothing happens. I hear nothing. Can someone guide me on this one? Tnx!

**Comment by rudeog** [comment]
Hi, what DAW and platform are you on?

**Comment by asafcha** [comment]
Hi, I'm using FL 20.8 on a mac BigSur

**Comment by asafcha** [comment]
If I understand correctly, Stochas is a sequencer that I can add to any vst on my DAW, right? it has no sound of its own, it supposes to add a sequnce on other vst. How do I do that? Thanks for helping

**Comment by rudeog** [comment]
That is correct. It does work on FL Studio, however there is some midi routing you need to do. Back when stochas was commercial, we had this video that described how to get this going in FL. Older version of FL so situation might have changed, however might be useful: https://www.youtube.com/watch?v=dWzrxjpL8p0

**Comment by asafcha** [comment]
Thank you Andrew, I'll dig into this soon.👍.

**Comment by asafcha** [comment]
Thanks again, it's working now. Maybe you should add an intro tip for this basic setup.

**Comment by rudeog** [comment]
Thanks Asaf. If you have time to write a paragraph on how you got it working, I can add it to the Q&A section.

**Comment by asafcha** [comment]
Sure. Here goes: 

Open Stochas>*General settings>Midi>Apply Output port 1 (#)
Open VST player>*General settings>Midi> Apply Input port 1 (#) 

*General Setting of the plugin

![צילום מסך 2021-01-20 ב-17 24 40](https://user-images.githubusercontent.com/1404547/105196772-a5a6ae00-5b44-11eb-9970-e3061423e878.png)

**Comment by rudeog** [comment]
Thanks! I've added it to the faq
