### ISSUE TITLE
STOCHAS CONSTANTLY DE-ACTIVATING

### ISSUE THREAD

**Issue by Protocol-b** [surge-synthesizer/stochas#67]
Hi all!  I purchased Stochas some time back, but it repeatedly de-activates itself and insists I re-register it.  However, I'm unable to, either online or offline.  I re-downloaded it recently hoping that since it has gone open source, the security check may have been bypassed, but no luck.  Stochas is the best stepper I have ever used but it hates me.  I'm ready to delete it permanently.  Can anyone advise on how to make it stop abusing me?  Thank you!  :)

**Comment by rudeog** [comment]
All the licensing has been removed, so if it's asking you to reactivate it, then it's likely you are still seeing the commercial version. I'd advise uninstalling it. Even go so far as to make sure that stochas.dll is not sitting around anywhere on your hard drive. Then install using the latest developer install from the github releases.

**Comment by Protocol-b** [comment]
Ah, I found my confusion - it is no longer available as a a VST2, but I kept re-instantiating the old VST2.  Sadly neither of my DAW's accepts VST3 (And MUTools / LiveProfessor should address that already) , but I'll see if the AU version will do it - thank you so much!  This has been bothering me for ages - truly appreciated rudeog!
