### ISSUE TITLE
Feature Request: Split single steps

### ISSUE THREAD

**Issue by johannesmenzel** [surge-synthesizer/stochas#72]
Hey, would it be possible to split single steps into partial notes? Like having a 16th note groove and split some notes into half to have 32th or 4th into quintuplets.

**Comment by mkruselj** [comment]
You can do this with MSEG.

**Comment by johannesmenzel** [comment]
Thanks for anwering, I honestly don't know that. Or do you mean it as the concept (of multi segment envelope generation)? This would not come so handy in editing fine probabilistic jazz grooves with real drum samples or similar.

**Comment by baconpaul** [comment]
I think @mkruselj might have answered a stochas question with a surge answer

**Comment by mkruselj** [comment]
Doh haha, sorry, I totally didn't see the repository to which this issue belongs. Apologies!

**Comment by johannesmenzel** [comment]
Ok, cool that we figured that out. Would that be hard to implement?

**Comment by rudeog** [comment]
The retrigger feature will now allow you to do this. It is in the developer release now and will be in the next full release.
