### ISSUE TITLE
Mono mode apparently doesn't apply probabilities (VST3)

### ISSUE THREAD

**Issue by giohappy** [surge-synthesizer/stochas#75]
Probabilities apply in Poly mode, but if use the Mono mode with the following pattern the second cell always plays, which is unexpected.
I'm testing Stochas develper release as VST3 in Bitwig 3.

![image](https://user-images.githubusercontent.com/571129/119819285-7f2cc100-bef0-11eb-9d3c-ba9ecb47b39e.png)

**Comment by rudeog** [comment]
Hi,
Yes, this is the correct behavior. Mono mode means it will select a single note from the selected notes at that step position (you only have one note so it will always select it, unless you add a note at the 'Off' line in which case it will either play your C3 or your Off note, ie not play a note). Poly mode means it will just do a random determination as to whether a note is on or off based on its probability (allowing more than one note to possibly sound at a step position).

**Comment by giohappy** [comment]
Thanks @rudeog. Nice trick to use the Off note to have probabilities for single notes ;)
