### ISSUE TITLE
what is the probability of "low", "medium" "high"?

### ISSUE THREAD

**Issue by jtn191** [surge-synthesizer/stochas#82]
Low probability still feels about like 50%...where it could be 10-30%

**Comment by rudeog** [comment]
By default the values of low, medium and high are 20, 50 and 100 (if you switch to poly mode you could tweak the actual % values and switch back to mono I believe). In mono mode, what this means is that these are just weights. So eg if you had 3 notes turned on for "Low", they'd have an equal chance of playing ( 20 / (20+20+20) = 33% each). And if you have 3 notes on "Med", it would equate to the same thing. If you have one "Med" and one "High", the high would be 66% likely to play and the Med would be 33% ( high = 100 / (100+50) = 66%, Med = 50 / (100 + 50) = 33%)
