### ISSUE TITLE
Copy and paste between patterns

### ISSUE THREAD

**Issue by Modchik** [surge-synthesizer/stochas#84]
Loving the plugin! I'd like to be able to copy an paste my work from one pattern into another so that I can build upon the work already done rather than redrawing the whole pattern each time. This way I could start a song relatively simply and then change pattern via Reaper automation to have more complex beats or melodies at relevant points without having to re-enter the pattern from scratch each time I want to add a few notes to it.
Looking forward to seeing where this tool goes!

**Comment by rudeog** [comment]
Hi,
This is already possible. Click on the pattern you want to copy into, then click the edit button (top right), pattern tab, click the "copy cell data from another pattern" radio button and select the source pattern.

**Comment by Modchik** [comment]
So you can! Sorry about that. Excellent!
