### ISSUE TITLE
Nightly Version Number

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/stochas#9]
Hi @rudeog just putting a couple of things into GitHub issues to remember

Right now the default stochas issue is 0.9.0 which means the nightly build has a version number like "0.9.HEAD.abc1234"

I think (think) we probably want that to default to 1.3.HEAD.abc1234 but wanted to ask

**Comment by rudeog** [comment]
Yes 1.3.x would be perfect.

**Comment by baconpaul** [comment]
OK! Whoever commits next should change the default in the CMakeLists and close this issue then! And I'll set up the release pipelines soon - at least before the first automated release over here :)

**Comment by rudeog** [comment]
This is fixed
