### ISSUE TITLE
Only one instance per project in Logic Pro

### ISSUE THREAD

**Issue by trevormeier** [surge-synthesizer/stochas#91]
I'm trying the AU version of Stochas in Logic Pro 10.7. Whenever I load Stochas on a new track, any previous instances of Stochas on other tracks stop producing output.

**Comment by baconpaul** [comment]
M1 or intel out of curiosity!

**Comment by rudeog** [comment]
Unfortunately don't have Logic, so can't debug. Is there another way to rep this, eg garageband?

**Comment by baconpaul** [comment]
I can give it a whirl later tonight

**Comment by xoxo369** [comment]
Im on 10.5.1 and multiple instances work for me

**Comment by baconpaul** [comment]
I just trued Stochas 1.3.10 and LPX 10.8 and multi-instance was no problem also. Closing this.
