### ISSUE TITLE
Custom Color Scheme

### ISSUE THREAD

**Issue by johannes84ernst** [surge-synthesizer/stochas#93]
Hello, 

I'm really in love with Stochas. What an amazing sequencer! 

I just found the "custom" color scheme setting - but its the same color scheme as the dark one. 

Is there a possibility to download/install a custom color scheme or a way to change the colors inside the plugin? 

Best regards, 

Johannes

**Comment by rudeog** [comment]
Hi Johannes,
Switch to "custom" scheme. This will create a file called stochas.skin which will initially be the same scheme as the dark scheme. On windows, go in windows explorer bar and type %APPDATA%\AudioVitamins, on mac look in ~/Library/Application Support/AudioVitamins to find the file. It is a text file, and you can use html color codes, so easiest to find one of those sites that has a color picker that shows you the codes. The changes get picked up either when you reload stochas, or switch back and forth between standard and custom color.

**Comment by rudeog** [comment]
Here is the color scheme that I'm using which was created by one of the users on the discord ( @rovingeye ) which I am using right now. They have a zip file which has a few schemes (here is the link https://discord.com/channels/744319641211633774/751879869385932961/880589188368572508 and I should probably drop that somewhere on the website...).

<?xml version="1.0" encoding="UTF-8"?>

<PROPERTIES>
  <VALUE name="background" val="#1F1F1F"/>
  <VALUE name="stepDisabled" val="#000000"/>
  <VALUE name="stepOff" val="#2C2C2C"/>
  <VALUE name="recordButtonActive" val="#FF9300"/>
  <VALUE name="recordButtonPassive" val="#804900"/>
  <VALUE name="playIndicatorOff" val="#484848"/>
  <VALUE name="playIndicatorOn" val="#F1BB72"/>
  <VALUE name="button" val="#484848"/>
  <VALUE name="interact" val="#FF9300"/>
  <VALUE name="border" val="#000000"/>
  <VALUE name="stepNeverProb" val="#000000"/>
  <VALUE name="stepLowProb" val="#F1BB72"/>
  <VALUE name="stepMediumProb" val="#804900"/>
  <VALUE name="stepHighProb" val="#FF9300"/>
  <VALUE name="stepLowVel" val="#F1BB72"/>
  <VALUE name="stepMedVel" val="#804900"/>
  <VALUE name="stepHighVel" val="#FF9300"/>
  <VALUE name="noteEditable" val="#484848"/>
  <VALUE name="noteLocked" val="#0D0D0D"/>
  <VALUE name="toggleOff" val="#0D0D0D"/>
  <VALUE name="toggleOn" val="#FF9300"/>
  <VALUE name="measureStart" val="#000000"/>
  <VALUE name="beatStart" val="#161616"/>
  <VALUE name="grooveEdit" val="#FF9300"/>
  <VALUE name="ghostedNotes" val="0"/>
  <VALUE name="cellSelection" val="#868686"/>
  <VALUE name="chainPositive" val="#F5BE18"/>
  <VALUE name="chainNegative" val="#C20114"/>
  <VALUE name="chainPositiveSel" val="#F5BE18"/>
  <VALUE name="chainNegativeSel" val="#C20114"/>
  <VALUE name="alertBackground" val="#C20114"/>
</PROPERTIES>

**Comment by johannes84ernst** [comment]
Perfect, thanks a lot! This works like a charm 💯 
Such a great Plugin! Now with custom colors, amazing 👍

**Comment by johannes84ernst** [comment]
Here is my first try creating a dark theme... 

![Screenshot 2021-12-07 002235](https://user-images.githubusercontent.com/95656106/144938692-09a08641-1df7-4fc4-9a99-dbe2e1ffd381.jpg)

**Comment by johannes84ernst** [comment]
This is the text of the text file with the color values, if anybody is interested.. 

<PROPERTIES>
  <VALUE name="background" val="171824"/>
  <VALUE name="stepDisabled" val="2f314a"/>
  <VALUE name="stepOff" val="383540"/>
  <VALUE name="stepNeverProb" val="84a9ab"/>
  <VALUE name="stepLowProb" val="c9aa4d"/>
  <VALUE name="stepMediumProb" val="c26f1d"/>
  <VALUE name="stepHighProb" val="9c2222"/>
  <VALUE name="stepLowVel" val="93aec9"/>
  <VALUE name="stepMedVel" val="7094b8"/>
  <VALUE name="stepHighVel" val="376b9e"/>
  <VALUE name="playIndicatorOff" val="3d3e4c"/>
  <VALUE name="playIndicatorOn" val="e0d1e0"/>
  <VALUE name="noteEditable" val="3d3f4d"/>
  <VALUE name="noteLocked" val="3d3e4c"/>
  <VALUE name="toggleOff" val="2b2f3b"/>
  <VALUE name="toggleOn" val="160121"/>
  <VALUE name="button" val="38596b"/>
  <VALUE name="interact" val="add8bc"/>
  <VALUE name="border" val="0"/>
  <VALUE name="measureStart" val="b8a200"/>
  <VALUE name="beatStart" val="a34900"/>
  <VALUE name="grooveEdit" val="502263"/>
  <VALUE name="ghostedNotes" val="0"/>
  <VALUE name="cellSelection" val="ffffff"/>
  <VALUE name="chainPositive" val="00918d"/>
  <VALUE name="chainNegative" val="990817"/>
  <VALUE name="chainPositiveSel" val="009185"/>
  <VALUE name="chainNegativeSel" val="ad1525"/>
  <VALUE name="alertBackground" val="5e0622"/>
  <VALUE name="recordButtonActive" val="ff0000"/>
  <VALUE name="recordButtonPassive" val="5e0622"/>
</PROPERTIES>

**Comment by johannes84ernst** [comment]
<PROPERTIES>
  <VALUE name="background" val="171824"/>
  <VALUE name="stepDisabled" val="2f314a"/>
  <VALUE name="stepOff" val="383540"/>
  <VALUE name="stepNeverProb" val="84a9ab"/>
  <VALUE name="stepLowProb" val="c9aa4d"/>
  <VALUE name="stepMediumProb" val="c26f1d"/>
  <VALUE name="stepHighProb" val="9c2222"/>
  <VALUE name="stepLowVel" val="93aec9"/>
  <VALUE name="stepMedVel" val="7094b8"/>
  <VALUE name="stepHighVel" val="376b9e"/>
  <VALUE name="playIndicatorOff" val="3d3e4c"/>
  <VALUE name="playIndicatorOn" val="e0d1e0"/>
  <VALUE name="noteEditable" val="3d3f4d"/>
  <VALUE name="noteLocked" val="3d3e4c"/>
  <VALUE name="toggleOff" val="2b2f3b"/>
  <VALUE name="toggleOn" val="160121"/>
  <VALUE name="button" val="38596b"/>
  <VALUE name="interact" val="add8bc"/>
  <VALUE name="border" val="0"/>
  <VALUE name="measureStart" val="b8a200"/>
  <VALUE name="beatStart" val="a34900"/>
  <VALUE name="grooveEdit" val="502263"/>
  <VALUE name="ghostedNotes" val="0"/>
  <VALUE name="cellSelection" val="ffffff"/>
  <VALUE name="chainPositive" val="00918d"/>
  <VALUE name="chainNegative" val="990817"/>
  <VALUE name="chainPositiveSel" val="009185"/>
  <VALUE name="chainNegativeSel" val="ad1525"/>
  <VALUE name="alertBackground" val="5e0622"/>
  <VALUE name="recordButtonActive" val="ff0000"/>
  <VALUE name="recordButtonPassive" val="5e0622"/>
</PROPERTIES>

**Comment by johannes84ernst** [comment]
<VALUE name="background" val="171824"/>
  <VALUE name="stepDisabled" val="2f314a"/>
  <VALUE name="stepOff" val="383540"/>
  <VALUE name="stepNeverProb" val="84a9ab"/>
  <VALUE name="stepLowProb" val="c9aa4d"/>
  <VALUE name="stepMediumProb" val="c26f1d"/>
  <VALUE name="stepHighProb" val="9c2222"/>
  <VALUE name="stepLowVel" val="93aec9"/>
  <VALUE name="stepMedVel" val="7094b8"/>
  <VALUE name="stepHighVel" val="376b9e"/>
  <VALUE name="playIndicatorOff" val="3d3e4c"/>
  <VALUE name="playIndicatorOn" val="e0d1e0"/>
  <VALUE name="noteEditable" val="3d3f4d"/>
  <VALUE name="noteLocked" val="3d3e4c"/>
  <VALUE name="toggleOff" val="2b2f3b"/>
  <VALUE name="toggleOn" val="160121"/>
  <VALUE name="button" val="38596b"/>
  <VALUE name="interact" val="add8bc"/>
  <VALUE name="border" val="0"/>
  <VALUE name="measureStart" val="b8a200"/>
  <VALUE name="beatStart" val="a34900"/>
  <VALUE name="grooveEdit" val="502263"/>
  <VALUE name="ghostedNotes" val="0"/>
  <VALUE name="cellSelection" val="ffffff"/>
  <VALUE name="chainPositive" val="00918d"/>
  <VALUE name="chainNegative" val="990817"/>
  <VALUE name="chainPositiveSel" val="009185"/>
  <VALUE name="chainNegativeSel" val="ad1525"/>
  <VALUE name="alertBackground" val="5e0622"/>
  <VALUE name="recordButtonActive" val="ff0000"/>
  <VALUE name="recordButtonPassive" val="5e0622"/>

**Comment by johannes84ernst** [comment]
[stochas-skin-dark-v1.zip](https://github.com/surge-synthesizer/stochas/files/7664172/stochas-skin-dark-v1.zip)

**Comment by windowsrefund** [comment]
FYI, on GNU/Linux, the steps would be:
1. Activate "Cust..." in Settings/Color Scheme
2. ~/AudioVitamins/stochas.skin now exists.
3. Tweak or overwrite

The dark theme provided in the .zip above is great and it really deserves to be distributed in a release.
